version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-schema:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - news_board

networks:
  news_board:
    driver: bridge
