apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.api.name }}-deployment
  annotations:
    "helm.sh/hook-weight": "{{ .Values.api.weight }}"
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
{{/*      annotations:*/}}
{{/*        prometheus.io/scrape: "true"*/}}
{{/*        prometheus.io/path: "/metrics"*/}}
{{/*        prometheus.io/port: "5000"*/}}
      labels:
        app: {{ .Values.api.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.api.name }}-config
          resources:
            requests:
              memory: {{ .Values.api.resources.requests.memory }}
              cpu: {{ .Values.api.resources.requests.cpu }}
            limits:
              memory: {{ .Values.api.resources.limits.memory }}
              cpu: {{ .Values.api.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.api.internalPort }}