apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.credentials.user | b64enc }}
  postgres-password: {{ .Values.postgres.credentials.password | b64enc }}
  postgres-db: {{ .Values.postgres.credentials.db | b64enc }}