apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.credentials.db | b64enc }}