namespace: news-board
imagePullSecrets: github-registry

postgres:
  credentials:
    user: postgres-user
    password: postgres-pass
    db: news-api
  name: postgres
  replicas: 1
  weight: 2
  port: 5432
  image:
    name: postgres
    tag: 15
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  volume:
    capacity: 1000Mi

api:
  name: news-api
  replicas: 1
  weight: 4
  host: 0.0.0.0
  externalPort: 50051
  internalPort: 50051
  logLevel: info
  auth:
    passPepper: super_secret_pass_pepper
    secretKey: super_secret_sid_key
    secureRoutes: /news.NewsService/CreateArticle,/news.NewsService/DeleteArticle,/news.NewsService/UpdateArticle,/auth.AuthService/SignOut
  db:
    uri: postgresql://postgres-user:postgres-pass@postgres-service:5432/news-api
  image:
    name: news-api
    tag: latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"